[config.wallpaper]
command="swww"
arguments=["img", "--transition-type", "center", "--transition-step", "15", "--transition-fps", "60"]
set=true

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'