[config.wallpaper]
command="swww"
arguments=["img", "--transition-type", "center", "--transition-step", "15", "--transition-fps", "60"]
set=true

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.myshell]
input_path = '~/.config/matugen/templates/myshell-colors.json'
output_path = '~/.config/quickshell/myShell/Configs/colors.json'

[templates.kdeglobals]
input_path = '~/.config/matugen/templates/kdeglobals'
output_path = '~/.config/kdeglobals'

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.kdecolors]
input_path = "~/.config/matugen/templates/kde.colors"
output_path = '~/.local/share/color-schemes/MaterialYou.colors'